version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: stock_analysis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DJANGO_DB_NAME=stock_analysis
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=admin
      - DJANGO_DB_HOST=db
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data:
