databases:
  - name: stock_analysis_db
    plan: free
    databaseName: stock_analysis
    user: stock_analysis

services:
  - type: web
    plan: free
    name: stock_analysis
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn stock_analysis.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stock_analysis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4